from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


QueryMode = Literal["fast", "thinking"]


def normalize_query_mode(value: str | None) -> QueryMode:
    if isinstance(value, str) and value.strip().lower() == "thinking":
        return "thinking"
    return "fast"


class FilterCondition(BaseModel):
    field: str
    operator: str = "="
    value: Any


class DateRange(BaseModel):
    kind: str
    start: date | None = None
    end: date | None = None
    lookback_value: int | None = None
    lookback_unit: str | None = None


class ClarificationOptionSuggestion(BaseModel):
    """Suggested answer option generated by the LLM alongside a clarification question."""

    id: str
    label: str
    detail: str | None = None
    reason: str | None = None


class IntentPayload(BaseModel):
    raw_prompt: str
    metric: str | None = None
    dimensions: list[str] = Field(default_factory=list)
    filters: list[FilterCondition] = Field(default_factory=list)
    comparison: str | None = None
    date_range: DateRange | None = None
    visualization_preference: str | None = None
    ambiguities: list[str] = Field(default_factory=list)
    clarification_question: str | None = None
    clarification_options: list[ClarificationOptionSuggestion] = Field(default_factory=list)
    confidence: float = 0.0
    follow_up: bool = False


class SemanticMetricPayload(BaseModel):
    name: str | None = None
    aggregation: str | None = None
    unit: str | None = None


class SemanticDimensionPayload(BaseModel):
    name: str
    role: str = "category"


class SemanticColumnRolePayload(BaseModel):
    name: str
    role: str


class SemanticDataRolesPayload(BaseModel):
    x: str | None = None
    y: str | None = None
    series_key: str | None = None
    facet_key: str | None = None
    label: str | None = None
    value: str | None = None


class SemanticTimePayload(BaseModel):
    column: str | None = None
    granularity: str | None = None
    range: DateRange | None = None


class SemanticComparisonPayload(BaseModel):
    kind: str = "none"
    entities: list[str] = Field(default_factory=list)
    baseline_period: DateRange | None = None
    series_column: str | None = None
    facet_column: str | None = None


class SemanticFlagsPayload(BaseModel):
    is_time_series: bool = False
    is_comparison: bool = False
    is_ranking: bool = False
    is_share: bool = False
    top_n: int | None = None
    explicit_chart_request: bool = False


class QuerySemantics(BaseModel):
    intent: str | None = None
    visual_goal: str | None = None
    analysis_mode: str | None = None
    time_role: Literal["primary", "secondary", "none"] | None = None
    comparison_goal: str | None = None
    preferred_mark: Literal["line", "bar", "area", "point", "arc", "stat"] | None = None
    metric: SemanticMetricPayload | None = None
    dimensions: list[SemanticDimensionPayload] = Field(default_factory=list)
    columns: list[SemanticColumnRolePayload] = Field(default_factory=list)
    data_roles: SemanticDataRolesPayload | None = None
    time: SemanticTimePayload | None = None
    comparison: SemanticComparisonPayload | None = None
    filters: list[FilterCondition] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    ambiguities: list[str] = Field(default_factory=list)
    flags: SemanticFlagsPayload = Field(default_factory=SemanticFlagsPayload)
    visualization_hint: str | None = None
    confidence_score: float = 0.0
    clarification_needed: str | None = None


class DimensionMapping(BaseModel):
    key: str
    label: str
    expression: str
    alias: str
    requires_join: str | None = None


class FilterMapping(BaseModel):
    field: str
    expression: str
    operator: str
    value: Any
    requires_join: str | None = None


class SemanticMappingPayload(BaseModel):
    metric_key: str | None = None
    metric_expression: str | None = None
    metric_alias: str | None = None
    time_expression: str | None = None
    base_alias: str = "t0"
    dimension_mappings: list[DimensionMapping] = Field(default_factory=list)
    filter_mappings: list[FilterMapping] = Field(default_factory=list)
    tables: list[str] = Field(default_factory=list)
    base_table: str = "orders"
    joins: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    dialect: str


class ValidationPayload(BaseModel):
    valid: bool
    sql: str
    tables: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    trace: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    semantic_confidence_level: Literal["low", "medium", "high"] | None = None
    semantic_confidence_reasons: list[str] = Field(default_factory=list)


class ChartEncoding(BaseModel):
    x_field: str | None = None
    y_field: str | None = None
    series_field: str | None = None
    facet_field: str | None = None
    sort: str | None = None
    normalize: Literal["none", "percent", "index_100", "running_total"] | None = None
    series_limit: int | None = None
    category_limit: int | None = None
    top_n_strategy: Literal["top_plus_other", "top_only", "none"] | None = None
    value_format: str | None = None
    data_roles: SemanticDataRolesPayload | None = None


class QueryInterpretationMetric(BaseModel):
    name: str
    aggregation: str | None = None
    format: str | None = None


class QueryInterpretationDimension(BaseModel):
    name: str
    role: str = "category"


class QueryInterpretation(BaseModel):
    user_goal: str
    intent: str | None = None
    analysis_mode: str | None = None
    entities: list[str] = Field(default_factory=list)
    metrics: list[QueryInterpretationMetric] = Field(default_factory=list)
    dimensions: list[QueryInterpretationDimension] = Field(default_factory=list)
    time_dimension: str | None = None
    series_dimension: str | None = None
    requested_output: str = "chart"
    assumptions: list[str] = Field(default_factory=list)
    ambiguities: list[str] = Field(default_factory=list)
    confidence: float = 0.0
    short_explanation: str | None = None


class DecisionAlternative(BaseModel):
    type: str
    why_not: str


class DecisionSummary(BaseModel):
    selected_chart: str
    why: str
    reason_codes: list[str] = Field(default_factory=list)
    alternatives: list[DecisionAlternative] = Field(default_factory=list)
    confidence: float = 0.0


class ChartCandidate(BaseModel):
    type: str
    score: float
    why: str


class ChartSpec(BaseModel):
    chart_type: str
    title: str
    encoding: ChartEncoding
    options: dict[str, Any] = Field(default_factory=dict)
    data: dict[str, Any] | None = None
    variant: str | None = None
    explanation: str | None = None
    reason: str | None = None
    rule_id: str | None = None
    confidence: float | None = None
    semantic_intent: str | None = None
    analysis_mode: str | None = None
    visual_goal: str | None = None
    time_role: str | None = None
    comparison_goal: str | None = None
    preferred_mark: str | None = None
    alternatives: list[str] = Field(default_factory=list)
    candidates: list[ChartCandidate] = Field(default_factory=list)
    constraints_applied: list[str] = Field(default_factory=list)
    visual_load: int | None = None
    query_interpretation: QueryInterpretation | None = None
    decision_summary: DecisionSummary | None = None
    reason_codes: list[str] = Field(default_factory=list)


class QueryExecutionResult(BaseModel):
    sql: str
    rows: list[dict[str, Any]] = Field(default_factory=list)
    columns: list[str] = Field(default_factory=list)
    row_count: int = 0
    execution_time_ms: int = 0


class PromptRunRequest(BaseModel):
    prompt: str = Field(min_length=1)
    query_mode: QueryMode = "fast"
    llm_model_alias: str | None = None


class PromptRunResponse(BaseModel):
    notebook_id: str
    query_run_id: str
    prompt_cell_id: str
    generated_cell_ids: list[str] = Field(default_factory=list)
    status: str


class CellContent(BaseModel):
    model_config = ConfigDict(extra="allow")


class CellRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    notebook_id: str
    query_run_id: str | None = None
    type: str
    position: int
    content: dict[str, Any]
    created_at: datetime
    updated_at: datetime


class QueryRunRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    notebook_id: str
    prompt_cell_id: str
    prompt_text: str
    sql: str
    explanation: dict[str, Any]
    agent_trace: dict[str, Any]
    confidence: float
    execution_time_ms: int
    row_count: int
    status: str
    analysis_message: str | None = None
    error_message: str | None = None
    created_at: datetime


@dataclass
class ClarificationAnswerRecord:
    clarification_id: str
    ambiguity_type: str
    option_id: str | None = None
    option_label: str | None = None
    text_answer: str | None = None


@dataclass
class QueryContext:
    previous_intent: IntentPayload | None = None
    notebook_title: str = ""
    original_prompt: str = ""
    clarification_answers: list[ClarificationAnswerRecord] = field(default_factory=list)
